### ISSUE TITLE
Feature request: Progress Bar or Time Estimation

### ISSUE THREAD

**Issue by ni-todo-spot** [cbrown1234/analyse-json#1]
Hey!

I Found this project very useful for my ndjson analyses. Thank you for maintaining it.

I'd like to suggest a progress bar feature and or a time estimation.
Such features would be extremely helpful to me.

Thanks in advance!

**Comment by cbrown1234** [comment]
I did think about this before, and left it out because I believe knowing how many lines there are to be processed would require processing the input twice, and hence would likely slow down the program for large files. I'm also not sure is possible for lines piped from stdin as it's unbounded.

For now I've added a progress indicator showing how many have been processed, and the rate they're being processed, so if you have some external knowledge of the line length you can get a sense for the progress. E.g. use `wc -l` on the files.

Is this sufficient? Otherwise I could add a opt in option to pre-calculate the line length if targetting files, however this might not be perfect if the files change between reading, and would come with a performance hit

**Comment by ni-todo-spot** [comment]
Thanks for your reply!
I prefer velocity over the progress bar, so I respect your choice.
Let's just say it's nice to have. I still find this project very useful :)
